version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile

    container_name: test-web

    ports:
      - "8080:8080"

    depends_on:
      - mysql_service

    # Avoids having to download all dependencies every time
    volumes:
      - ~/.m2:/root/.m2

    working_dir: /app

    command: mvn -f ./pom.xml clean spring-boot:run


  mysql_service:
    image: mysql:8

    container_name: mysql_db

    restart: always

    environment:
      MYSQL_DATABASE: 'testdb'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'

    ports:
      - "3306"

    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  testdb:
